import type { Metadata } from 'next';
import './globals.css';
export const metadata: Metadata = {
    title: 'SkillCraft AI',
    description: 'Generated by Onlook',
    metadataBase: new URL('http://localhost:3000/'),
    icons: {
        icon: '/favicon.ico',
    },
};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="z.q9cq1">
            <body className="" data-oid="o7u4b4f">
                {children}
            </body>
        </html>
    );
}
