# 服务器配置
server:
  host: "127.0.0.1"
  port: "8080"

# 数据库配置
database:
  dsn: "root:zht20040723zht@tcp(127.0.0.1:3306)/ai_learning_db?charset=utf8mb4&parseTime=True&loc=Local"

# JWT 密钥
jwt:
  secret: "your-secret-key"